---
title: "Effects of Aggressive Baserunning in MiLB"
author: "Alexander Harriman"
date: "2024-06-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning = FALSE}
library(dplyr)
library(stringr)
library(tidyr)
library(weights)
library(beepr)
library(lubridate)
library(rvest)
library(xml2)
library(ggplot2)
library(ggpubr)
library(gt)
```


# Data Load State

```{r}
allData <- read.csv('2024 Full MiLB August 5.csv')

allData <- allData[-1]
allData <- allData[-1]
```


```{r}
closeGames <- allData |>
  distinct(paste(game_pk, startTime, endTime), .keep_all = TRUE) |>
  mutate(runs_scored = case_when(
    lead(game_pk) != game_pk ~ 0,
    about.halfInning == 'top' ~ result.awayScore - lead(result.awayScore), 
    about.halfInning == 'bottom' ~ result.homeScore - lead(result.homeScore),
    .default = 0
  ),
  halfInnNum = case_when(
    about.halfInning == 'top' ~ (2 * about.inning) - 1,
    about.halfInning == 'bottom' ~ (2 * about.inning)
  ))  |>
  group_by(game_pk) |>
  summarise(home_score = sum(ifelse(halfInnNum %% 2 == 0, runs_scored, 0)),
            homeTeam = home_team[1],
            away_score = sum(ifelse(halfInnNum %% 2 == 1, runs_scored, 0)),
            awayTeam = away_team[1])

closeGameFilter <- closeGames |>
  filter(abs(home_score - away_score) <= 1)

closeGameFilter
```


```{r}
filteredData <- allData |>
  filter(game_pk %in% closeGameFilter$game_pk)
```

```{r}
bipBaserunning <- filteredData |>
  distinct(paste(game_pk, startTime, endTime), .keep_all = TRUE) |>
  distinct(paste(game_pk, atBatIndex), .keep_all = TRUE) |>
  mutate(isRunner1B = ifelse(is.na(lead(matchup.postOnFirst.id)) == TRUE, 0, 1),
  isRunner2B = ifelse(is.na(lead(matchup.postOnSecond.id)) == TRUE, 0, 1),
  isRunner3B = ifelse(is.na(lead(matchup.postOnThird.id)) == TRUE, 0, 1)) |>
  mutate(eligibleSingle = ifelse(result.event == 'Single' & (isRunner1B == 1 | isRunner2B == 1) &
                        (grepl('to left fielder', result.description, fixed = TRUE) == TRUE | 
                         grepl('to center fielder', result.description, fixed = TRUE) == TRUE |
                         grepl('to right fielder', result.description, fixed = TRUE) == TRUE), 1, 0),
  eligibleDouble = ifelse(result.event == 'Double' & isRunner1B == 1 &
                        (grepl('to left fielder', result.description, fixed = TRUE) == TRUE | 
                         grepl('to center fielder', result.description, fixed = TRUE) == TRUE |
                         grepl('to right fielder', result.description, fixed = TRUE) == TRUE), 1, 0),
  eligibleFlyBall = ifelse(result.event %in% c('Flyout', 'Sac Fly', 'Sac Fly Double Play') & 
                        (isRunner1B == 1 | isRunner2B == 1 | isRunner3B == 1) &
                        (grepl('to left fielder', result.description, fixed = TRUE) == TRUE | 
                         grepl('to center fielder', result.description, fixed = TRUE) == TRUE |
                         grepl('to right fielder', result.description, fixed = TRUE) == TRUE), 1, 0)) |>
  mutate(runner1B = ifelse(isRunner1B == 1, lead(matchup.postOnFirst.fullName), NA),
         runner2B = ifelse(isRunner2B == 1, lead(matchup.postOnSecond.fullName), NA),
         runner3B = ifelse(isRunner3B == 1, lead(matchup.postOnThird.fullName), NA))
```


**The below code chunk takes ~15 minutes to run.**

```{r}
for(i in 1:dim(bipBaserunning)[1]){
  bipBaserunning$runner1BScore[i] = ifelse(grepl(paste(bipBaserunning$runner1B[i], "scores."), bipBaserunning$result.description[i]) == TRUE, 1, 0)
  bipBaserunning$runner1BSecond[i] = ifelse(grepl(paste(bipBaserunning$runner1B[i], "to 2nd."), bipBaserunning$result.description[i]) == TRUE, 1, 0)
  bipBaserunning$runner1BThird[i] = ifelse(grepl(paste(bipBaserunning$runner1B[i], "to 3rd."), bipBaserunning$result.description[i]) == TRUE, 1, 0)
  bipBaserunning$runner2BScore[i] = ifelse(grepl(paste(bipBaserunning$runner2B[i], "scores."), bipBaserunning$result.description[i]) == TRUE, 1, 0)
  bipBaserunning$runner2BThird[i] = ifelse(grepl(paste(bipBaserunning$runner2B[i], "to 3rd."), bipBaserunning$result.description[i]) == TRUE, 1, 0)
  bipBaserunning$runner3BScore[i] = ifelse(grepl(paste(bipBaserunning$runner3B[i], "scores."), bipBaserunning$result.description[i]) == TRUE, 1, 0)
}

bipBaserunning
```

```{r}
bipBaserunning <- bipBaserunning |>
  mutate(Org = case_when(
    batting_team %in% c('Norfolk Tides', 'Bowie Baysox', 'Aberdeen IronBirds', 'Delmarva Shorebirds', 'Baltimore Orioles') ~ 'BAL',
    batting_team %in% c('Worcester Red Sox', 'Portland Sea Dogs', 'Greenville Drive', 'Salem Red Sox', 'Boston Red Sox') ~ 'BOS',
    batting_team %in% c('Scranton/Wilkes-Barre RailRiders', 'Somerset Patriots', 'Hudson Valley Renegades', 'Tampa Tarpons', 'New York Yankees') ~ 'NYY',
    batting_team %in% c('Durham Bulls', 'Montgomery Biscuits', 'Bowling Green Hot Rods', 'Charleston RiverDogs', 'Tampa Bay Rays') ~ 'TB',
    batting_team %in% c('Buffalo Bisons', 'New Hampshire Fisher Cats', 'Vancouver Canadians', 'Dunedin Blue Jays', 'Toronto Blue Jays') ~ 'TOR',
    batting_team %in% c('Charlotte Knights', 'Birmingham Barons', 'Winston-Salem Dash', 'Kannapolis Cannon Ballers', 'Chicago White Sox') ~ 'CWS',
    batting_team %in% c('Columbus Clippers', 'Akron RubberDucks', 'Lake County Captains', 'Lynchburg Hillcats', 'Cleveland Guardians') ~ 'CLE',
    batting_team %in% c('Toledo Mud Hens', 'Erie SeaWolves', 'West Michigan Whitecaps', 'Lakeland Flying Tigers', 'Detroit Tigers') ~ 'DET',
    batting_team %in% c('Omaha Storm Chasers', 'Northwest Arkansas Naturals', 'Quad Cities River Bandits', 'Columbia Fireflies', 'Kansas City Royals') ~ 'KC',
    batting_team %in% c('St. Paul Saints', 'Wichita Wind Surge', 'Cedar Rapids Kernels', 'Fort Myers Mighty Mussels', 'Minnesota Twins') ~ 'MIN',
    batting_team %in% c('Sugar Land Space Cowboys', 'Corpus Christi Hooks', 'Asheville Tourists', 'Fayetteville Woodpeckers', 'Houston Astros') ~ 'HOU',
    batting_team %in% c('Salt Lake Bees', 'Rocket City Trash Pandas', 'Tri-City Dust Devils', 'Inland Empire 66ers', 'Los Angeles Angels') ~ 'LAA',
    batting_team %in% c('Las Vegas Aviators', 'Midland RockHounds', 'Lansing Lugnuts', 'Stockton Ports', 'Oakland Athletics') ~ 'OAK',
    batting_team %in% c('Tacoma Rainiers', 'Arkansas Travelers', 'Everett AquaSox', 'Modesto Nuts', 'Seattle Mariners') ~ 'SEA',
    batting_team %in% c('Round Rock Express', 'Frisco RoughRiders', 'Hickory Crawdads', 'Down East Wood Ducks', 'Texas Rangers') ~ 'TEX',
    batting_team %in% c('Gwinnett Stripers', 'Mississippi Braves', 'Rome Emperors', 'Augusta GreenJackets', 'Atlanta Braves') ~ 'ATL',
    batting_team %in% c('Jacksonville Jumbo Shrimp', 'Pensacola Blue Wahoos', 'Beloit Sky Carp', 'Jupiter Hammerheads', 'Miami Marlins') ~ 'MIA',
    batting_team %in% c('Syracuse Mets', 'Binghamton Rumble Ponies', 'Brooklyn Cyclones', 'St. Lucie Mets', 'New York Mets') ~ 'NYM',
    batting_team %in% c('Lehigh Valley IronPigs', 'Reading Fightin Phils', 'Jersey Shore BlueClaws', 'Clearwater Threshers', 'Philadelphia Phillies') ~ 'PHI',
    batting_team %in% c('Rochester Red Wings', 'Harrisburg Senators', 'Wilmington Blue Rocks', 'Fredericksburg Nationals', 'Washington Nationals') ~ 'WSH',
    batting_team %in% c('Iowa Cubs', 'Tennessee Smokies', 'South Bend Cubs', 'Myrtle Beach Pelicans', 'Chicago Cubs') ~ 'CHC',
    batting_team %in% c('Louisville Bats', 'Chattanooga Lookouts', 'Dayton Dragons', 'Daytona Tortugas', 'Cincinnati Reds') ~ 'CIN',
    batting_team %in% c('Nashville Sounds', 'Biloxi Shuckers', 'Wisconsin Timber Rattlers', 'Carolina Mudcats', 'Milwaukee Brewers') ~ 'MIL',
    batting_team %in% c('Indianapolis Indians', 'Altoona Curve', 'Greensboro Grasshoppers', 'Bradenton Marauders', 'Pittsburgh Pirates') ~ 'PIT',
    batting_team %in% c('Memphis Redbirds', 'Springfield Cardinals', 'Peoria Chiefs', 'Palm Beach Cardinals', 'St. Louis Cardinals') ~ 'STL',
    batting_team %in% c('Reno Aces', 'Amarillo Sod Poodles', 'Hillsboro Hops', 'Visalia Rawhide', 'Arizona Diamondbacks') ~ 'AZ',
    batting_team %in% c('Albuquerque Isotopes', 'Hartford Yard Goats', 'Spokane Indians', 'Fresno Grizzlies', 'Colorado Rockies') ~ 'COL',
    batting_team %in% c('Oklahoma City Baseball Club', 'Tulsa Drillers', 'Great Lakes Loons', 'Rancho Cucamonga Quakes', 'Los Angeles Dodgers') ~ 'LAD',
    batting_team %in% c('El Paso Chihuahuas', 'San Antonio Missions', 'Fort Wayne TinCaps', 'Lake Elsinore Storm', 'San Diego Padres') ~ 'SD',
    batting_team %in% c('Sacramento River Cats', 'Richmond Flying Squirrels', 'Eugene Emeralds', 'San Jose Giants', 'San Francisco Giants') ~ 'SF',
    .default = 'MLB'))
```


```{r}
bipTeamTable <- bipBaserunning |>
  mutate(runs_scored = case_when(
    lead(game_pk) != game_pk ~ 0,
    about.halfInning == 'top' ~ result.awayScore - lead(result.awayScore), 
    about.halfInning == 'bottom' ~ result.homeScore - lead(result.homeScore),
    .default = 0
  ),
  halfInnNum = case_when(
    about.halfInning == 'top' ~ (2 * about.inning) - 1,
    about.halfInning == 'bottom' ~ (2 * about.inning)
  ))  |>
  group_by(game_pk, batting_team) |>
  summarise(singlesOF = sum(eligibleSingle),
            doublesOF = sum(eligibleDouble),
            flyBallOF = sum(eligibleFlyBall),
            single13 = sum(ifelse(eligibleSingle == 1 & runner1BThird == 1, 1, 0)),
            single2H = sum(ifelse(eligibleSingle == 1 & runner2BScore == 1, 1, 0)),
            double1H = sum(ifelse(eligibleDouble == 1 & runner1BScore == 1, 1, 0)),
            flyball12 = sum(ifelse(eligibleFlyBall == 1 & runner1BSecond == 1, 1, 0)),
            flyball23 = sum(ifelse(eligibleFlyBall == 1 & runner2BThird == 1, 1, 0)),
            flyball3H = sum(ifelse(eligibleFlyBall == 1 & runner3BScore == 1, 1, 0))) |>
  ungroup() |>
  mutate(singleAdvances = single13 + single2H,
         doubleAdvances = double1H,
         flyballAdvances = flyball12 + flyball23 + flyball3H) |>
  mutate(singleRate = round((100.0*singleAdvances) / singlesOF, 1),
         doubleRate = round((100.0*doubleAdvances) / doublesOF, 1),
         flyballRate = round((100.0*flyballAdvances) / flyBallOF, 1))

bipTeamTable

```




```{r}
summaryTable <- bipTeamTable |>
  group_by(game_pk) |>
  summarise(aggroSingle = case_when(
    singleRate[1] > singleRate[2] ~ batting_team[1],
    singleRate[2] > singleRate[1] ~ batting_team[2],
    singleRate[1] == singleRate[2] ~ 'Tie',
    .default = 'Tie'
  ),
  aggroDouble = case_when(
    doubleRate[1] > doubleRate[2] ~ batting_team[1],
    doubleRate[2] > doubleRate[1] ~ batting_team[2],
    doubleRate[1] == doubleRate[2] ~ 'Tie',
    .default = 'Tie'
  ),
  aggroFB = case_when(
    flyballRate[1] > flyballRate[2] ~ batting_team[1],
    flyballRate[2] > flyballRate[1] ~ batting_team[2],
    flyballRate[1] == flyballRate[2] ~ 'Tie',
    .default = 'Tie'
  ))

summaryTable
```


# Find Game Winners


```{r}
gameWinner <- closeGameFilter |>
  mutate(Winner = ifelse(home_score > away_score, homeTeam, awayTeam)) |>
  select(game_pk, Winner)


joinedData <- inner_join(summaryTable, gameWinner, by = 'game_pk')

joinedData
```



```{r}
finalResults <- data.frame(
  singleWinner = round(100.0*sum(ifelse(joinedData$aggroSingle == joinedData$Winner, 1, 0)) / sum(ifelse(joinedData$aggroSingle != 'Tie', 1, 0)),1),
  doubleWinner = round(100.0*sum(ifelse(joinedData$aggroDouble == joinedData$Winner, 1, 0)) / sum(ifelse(joinedData$aggroDouble != 'Tie', 1, 0)),1),
  fbWinner = round(100.0*sum(ifelse(joinedData$aggroFB == joinedData$Winner, 1, 0)) / sum(ifelse(joinedData$aggroFB != 'Tie', 1, 0)),1)
) |>
  mutate(singleLoser = 100.0 - singleWinner,
         doubleLoser = 100.0 - doubleWinner,
         fbLoser = 100.0 - fbWinner)

finalResults
```


```{r}
finalFrame <- data.frame(
  Result = c('Win', 'Lose'),
  Singles = c(finalResults$singleWinner, finalResults$singleLoser),
  Doubles = c(finalResults$doubleWinner, finalResults$doubleLoser),
  `Fly Balls` = c(finalResults$fbWinner, finalResults$fbLoser)
  
)

finalFrame
```



```{r}
cleanType <- finalFrame |>
  gt() |>
  tab_header(title = md('**Results of Aggressive Baserunning in 1 Run Games**')) |>
  cols_align(align = 'center', columns = c('Singles', 'Doubles', 'Fly.Balls')) |>
  cols_label(Fly.Balls = 'Fly Balls') |>
  opt_stylize(style = 5, color = 'blue') |>
  cols_width(everything() ~ px(125)) |>
  tab_footnote(footnote = '2024 Full-Season MiLB, as of August 5')

cleanType
```

