-- Query 1
SELECT mcp.PLAYER_NAME_LF AS player, sum(mcp.IP) AS inn
FROM rpt.VIEW_MLB_CURPIT_PLAYER AS mcp
WHERE mcp.ORGANIZATION_ABBREV = 'TEX' AND mcp.COMPETITION_LEVEL = 'A+' AND mcp.GAME_YEAR = 2022
GROUP BY player
ORDER BY inn DESC;

-- Query 2
SELECT mcp.PLAYER_NAME_LF AS player, sum(mcp.SO) AS K
FROM rpt.VIEW_MLB_CURPIT_PLAYER AS mcp
WHERE mcp.ORGANIZATION_ABBREV = 'TEX' AND mcp.COMPETITION_LEVEL = 'AA' AND mcp.GAME_YEAR = 2022 AND mcp.IP >= 50
GROUP BY player
ORDER BY K DESC;

-- Query 3 (Split into multiple parts)
SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.PITCH_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Fastball' AND wheel.PITCH_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;

SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.PITCH_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Slider' AND wheel.PITCH_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;

SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.PITCH_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Sinker' AND wheel.PITCH_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;

SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.PITCH_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Changeup' AND wheel.PITCH_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;

SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.PITCH_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Curveball' AND wheel.PITCH_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;

--LVA
SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.LVA_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Fastball' AND wheel.LVA_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;

SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.LVA_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Slider' AND wheel.LVA_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;

SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.LVA_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Sinker' AND wheel.LVA_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;

SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.LVA_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Changeup' AND wheel.LVA_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;

SELECT wheel.PITCHER_NAME_LAST_FIRST AS pname, avg(wheel.LVA_GRADE) AS grade 
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel.PITCHER_ORGANIZATION_ABBREV = 'TEX' AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('Rk','A','A+','AA','AAA')
	AND wheel.PITCH_TYPE = 'Curveball' AND wheel.LVA_GRADE IS NOT NULL 
GROUP BY pname 
ORDER BY grade DESC;



--Query 4
SELECT pitcher.PITCH_TYPE AS pitch, avg(pitcher.EFFECTIVE_VELOCITY), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Winn, Cole' AND pitcher.EFFECTIVE_VELOCITY < 75
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL 
GROUP BY pitch
UNION ALL 
SELECT pitcher.PITCH_TYPE AS pitch, avg(pitcher.EFFECTIVE_VELOCITY), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Winn, Cole' AND pitcher.EFFECTIVE_VELOCITY < 80 AND pitcher.EFFECTIVE_VELOCITY >= 75
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL 
GROUP BY pitch
UNION ALL
SELECT pitcher.PITCH_TYPE AS pitch, avg(pitcher.EFFECTIVE_VELOCITY), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Winn, Cole' AND pitcher.EFFECTIVE_VELOCITY < 85 AND pitcher.EFFECTIVE_VELOCITY >= 80
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL 
GROUP BY pitch
UNION ALL
SELECT pitcher.PITCH_TYPE AS pitch, avg(pitcher.EFFECTIVE_VELOCITY), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Winn, Cole' AND pitcher.EFFECTIVE_VELOCITY < 90 AND pitcher.EFFECTIVE_VELOCITY >= 85
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL 
GROUP BY pitch
UNION ALL 
SELECT pitcher.PITCH_TYPE AS pitch, avg(pitcher.EFFECTIVE_VELOCITY), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Winn, Cole' AND pitcher.EFFECTIVE_VELOCITY >= 90
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL 
GROUP BY pitch;


--Query 5
SELECT pitcher.PITCHER_NAME_LAST_FIRST, avg(pitcher.HORIZONTAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Weems, Avery' AND pitcher.HORIZONTAL_BREAK < 5 AND pitcher.HORIZONTAL_BREAK > 0 AND pitcher.PITCH_TYPE = 'Sinker'
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL
GROUP BY pitcher.PITCHER_NAME_LAST_FIRST
UNION ALL
SELECT pitcher.PITCHER_NAME_LAST_FIRST, avg(pitcher.HORIZONTAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Weems, Avery' AND pitcher.HORIZONTAL_BREAK < 10 AND pitcher.HORIZONTAL_BREAK > 5 AND pitcher.PITCH_TYPE = 'Sinker'
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL 
GROUP BY pitcher.PITCHER_NAME_LAST_FIRST
UNION ALL
SELECT pitcher.PITCHER_NAME_LAST_FIRST, avg(pitcher.HORIZONTAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Weems, Avery' AND pitcher.HORIZONTAL_BREAK < 15 AND pitcher.HORIZONTAL_BREAK > 10 AND pitcher.PITCH_TYPE = 'Sinker'
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL 	
GROUP BY pitcher.PITCHER_NAME_LAST_FIRST
UNION ALL
SELECT pitcher.PITCHER_NAME_LAST_FIRST, avg(pitcher.HORIZONTAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Weems, Avery' AND pitcher.HORIZONTAL_BREAK < 20 AND pitcher.HORIZONTAL_BREAK > 15 AND pitcher.PITCH_TYPE = 'Sinker'
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL
GROUP BY pitcher.PITCHER_NAME_LAST_FIRST
UNION ALL
SELECT pitcher.PITCHER_NAME_LAST_FIRST, avg(pitcher.HORIZONTAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Weems, Avery' AND pitcher.HORIZONTAL_BREAK > 20 AND pitcher.PITCH_TYPE = 'Sinker'
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.WRC IS NOT NULL
GROUP BY pitcher.PITCHER_NAME_LAST_FIRST;


--Query 6
SELECT pitcher.PITCHER_TEAM_NAME_ABBREV, avg(pitcher.INDUCED_VERTICAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Ragans, Cole' AND pitcher.INDUCED_VERTICAL_BREAK < 5 AND pitcher.INDUCED_VERTICAL_BREAK > 0
	AND pitcher.PITCH_TYPE = 'Cutter' AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL 
	AND pitcher.WRC IS NOT NULL 
GROUP BY pitcher.PITCHER_TEAM_NAME_ABBREV
UNION ALL
SELECT pitcher.PITCHER_TEAM_NAME_ABBREV, avg(pitcher.INDUCED_VERTICAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Ragans, Cole' AND pitcher.INDUCED_VERTICAL_BREAK < 10 AND pitcher.INDUCED_VERTICAL_BREAK > 5
	AND pitcher.PITCH_TYPE = 'Cutter' AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL 
	AND pitcher.WRC IS NOT NULL 
GROUP BY pitcher.PITCHER_TEAM_NAME_ABBREV
UNION ALL
SELECT pitcher.PITCHER_TEAM_NAME_ABBREV, avg(pitcher.INDUCED_VERTICAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Ragans, Cole' AND pitcher.INDUCED_VERTICAL_BREAK < 15 AND pitcher.INDUCED_VERTICAL_BREAK > 10
	AND pitcher.PITCH_TYPE = 'Cutter' AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL 
	AND pitcher.WRC IS NOT NULL 
GROUP BY pitcher.PITCHER_TEAM_NAME_ABBREV
UNION ALL
SELECT pitcher.PITCHER_TEAM_NAME_ABBREV, avg(pitcher.INDUCED_VERTICAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Ragans, Cole' AND pitcher.INDUCED_VERTICAL_BREAK < 20 AND pitcher.INDUCED_VERTICAL_BREAK > 15
	AND pitcher.PITCH_TYPE = 'Cutter' AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL 
	AND pitcher.WRC IS NOT NULL 
GROUP BY pitcher.PITCHER_TEAM_NAME_ABBREV
UNION ALL 
SELECT pitcher.PITCHER_TEAM_NAME_ABBREV, avg(pitcher.INDUCED_VERTICAL_BREAK), avg(pitcher.WOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC_PLUS), avg(pitcher.WRC)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Ragans, Cole' AND pitcher.INDUCED_VERTICAL_BREAK > 20
	AND pitcher.PITCH_TYPE = 'Cutter' AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL 
	AND pitcher.WRC IS NOT NULL 
GROUP BY pitcher.PITCHER_TEAM_NAME_ABBREV;


--Query 7
SELECT pitcher.IS_HIGH, pitcher.IS_LOW, avg(pitcher.WOBA), avg(pitcher.XWOBA), avg(pitcher.RUN_VALUE_24), avg(pitcher.WRC), avg(pitcher.WRC_PLUS)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS pitcher
WHERE pitcher.PITCHER_NAME_LAST_FIRST = 'Leiter, Jack' AND pitcher.PITCH_TYPE = 'Fastball'
	AND pitcher.WOBA IS NOT NULL AND pitcher.RUN_VALUE_24 IS NOT NULL AND pitcher.WRC_PLUS IS NOT NULL AND pitcher.XWOBA IS NOT NULL 
GROUP BY pitcher.IS_HIGH, pitcher.IS_LOW;


--Query 8
SELECT p.PITCH_TYPE, avg(p.WOBA), avg(p.XWOBA), avg(p.RUN_VALUE_24) AS rv, avg(p.WRC), avg(p.WRC_PLUS)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS p
INNER JOIN rpt.VIEW_AGG_HIT_PLAYER AS h 
	ON h.TXR_PLAYER_ID = p.BATTER_TXR_PLAYER_ID 
WHERE p.PITCHER_NAME_LAST_FIRST = 'Bradford, Cody' AND h.BATS = 'R'
	AND p.WOBA IS NOT NULL AND p.RUN_VALUE_24 IS NOT NULL AND p.WRC_PLUS IS NOT NULL AND p.XWOBA IS NOT NULL 
GROUP BY p.PITCH_TYPE
ORDER BY rv DESC;


--Query 9
SELECT p.PITCH_TYPE, count(1) AS pitch_count, avg(p.WOBA), avg(p.XWOBA), avg(p.RUN_VALUE_24) AS rv, avg(p.WRC), avg(p.WRC_PLUS)
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS p
WHERE TRUE IN (p.HAS_10_COUNT, p.HAS_20_COUNT, p.HAS_30_COUNT, p.HAS_31_COUNT, p.HAS_21_COUNT) 
	AND p.WOBA IS NOT NULL AND p.RUN_VALUE_24 IS NOT NULL AND p.WRC_PLUS IS NOT NULL AND p.XWOBA IS NOT NULL AND p.PITCHER_NAME_LAST_FIRST = 'Kent, Zak'
GROUP BY p.PITCH_TYPE 
ORDER BY pitch_count desc;

--Query 10
--Total
SELECT cur.ORGANIZATION_ABBREV, RANK() OVER(ORDER BY avg(cur.BB_RATE) DESC) AS walk, 
	RANK() OVER(ORDER BY avg(cur.SO_RATE)) AS k, 
	RANK() OVER(ORDER BY avg((((13*cur.HR + 3*cur.BB - 2*cur.SO) / cur.IP) + 3.112))) AS fip
FROM rpt.VIEW_MLB_CURPIT_PLAYER AS cur
WHERE cur.GAME_YEAR = 2022 AND cur.ip > 0 
	AND cur.COMPETITION_LEVEL_ABBREV IN ('A', 'A+', 'AA', 'AAA')
GROUP BY cur.ORGANIZATION_ABBREV;

--Separate Minor League Levels
SELECT cur.ORGANIZATION_ABBREV, cur.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(cur.BB_RATE) DESC) AS walk, 
	RANK() OVER(ORDER BY avg(cur.SO_RATE)) AS k, 
	RANK() OVER(ORDER BY avg((((13*cur.HR + 3*cur.BB - 2*cur.SO) / cur.IP) + 3.112))) AS fip
FROM rpt.VIEW_MLB_CURPIT_PLAYER AS cur
WHERE cur.GAME_YEAR = 2022 AND cur.ip > 0 
	AND cur.COMPETITION_LEVEL_ABBREV = 'A'
GROUP BY cur.COMPETITION_LEVEL_ABBREV, cur.ORGANIZATION_ABBREV
UNION ALL
SELECT cur.ORGANIZATION_ABBREV, cur.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(cur.BB_RATE) DESC) AS walk, 
	RANK() OVER(ORDER BY avg(cur.SO_RATE)) AS k, 
	RANK() OVER(ORDER BY avg((((13*cur.HR + 3*cur.BB - 2*cur.SO) / cur.IP) + 3.112))) AS fip
FROM rpt.VIEW_MLB_CURPIT_PLAYER AS cur
WHERE cur.GAME_YEAR = 2022 AND cur.ip > 0 
	AND cur.COMPETITION_LEVEL_ABBREV = 'A+'
GROUP BY cur.COMPETITION_LEVEL_ABBREV, cur.ORGANIZATION_ABBREV
UNION ALL
SELECT cur.ORGANIZATION_ABBREV, cur.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(cur.BB_RATE) DESC) AS walk, 
	RANK() OVER(ORDER BY avg(cur.SO_RATE)) AS k, 
	RANK() OVER(ORDER BY avg((((13*cur.HR + 3*cur.BB - 2*cur.SO) / cur.IP) + 3.112))) AS fip
FROM rpt.VIEW_MLB_CURPIT_PLAYER AS cur
WHERE cur.GAME_YEAR = 2022 AND cur.ip > 0 
	AND cur.COMPETITION_LEVEL_ABBREV = 'AA'
GROUP BY cur.COMPETITION_LEVEL_ABBREV, cur.ORGANIZATION_ABBREV
UNION ALL
SELECT cur.ORGANIZATION_ABBREV, cur.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(cur.BB_RATE) DESC) AS walk, 
	RANK() OVER(ORDER BY avg(cur.SO_RATE)) AS k, 
	RANK() OVER(ORDER BY avg((((13*cur.HR + 3*cur.BB - 2*cur.SO) / cur.IP) + 3.112))) AS fip
FROM rpt.VIEW_MLB_CURPIT_PLAYER AS cur
WHERE cur.GAME_YEAR = 2022 AND cur.ip > 0 
	AND cur.COMPETITION_LEVEL_ABBREV = 'AAA'
GROUP BY cur.COMPETITION_LEVEL_ABBREV, cur.ORGANIZATION_ABBREV;


-- Query 11
SELECT wheel.HOME_ORGANIZATION_ABBREV, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.IS_STRIKE = TRUE THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS strike_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_RESULT = 'Swinging Strike' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS swing_k_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE = 'Fastball' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS fastball_rate,
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE = 'Fastball' THEN 0 ELSE 1 END) / count(1)) DESC) AS breakball_rate
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel."YEAR" = 2022 
	AND wheel.IS_STRIKE IS NOT NULL AND wheel.PITCH_TYPE IS NOT NULL AND wheel.PITCH_RESULT IS NOT NULL
	AND wheel.HOME_COMPETITION_LEVEL_ABBREV IN ('A', 'A+', 'AA', 'AAA')
GROUP BY wheel.HOME_ORGANIZATION_ABBREV;


--Separate Minor League Levels
SELECT wheel.HOME_ORGANIZATION_ABBREV, wheel.HOME_COMPETITION_LEVEL_ABBREV, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.IS_STRIKE = TRUE THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS strike_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_RESULT = 'Swinging Strike' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS swing_k_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE = 'Fastball' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS fastball_rate,
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE <> 'Fastball' THEN 1 ELSE 0 END) / count(1)) DESC) AS breakball_rate
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel."YEAR" = 2022 
	AND wheel.IS_STRIKE IS NOT NULL AND wheel.PITCH_TYPE IS NOT NULL AND wheel.PITCH_RESULT IS NOT NULL
	AND wheel.HOME_COMPETITION_LEVEL_ABBREV = 'A'
GROUP BY wheel.HOME_COMPETITION_LEVEL_ABBREV, wheel.HOME_ORGANIZATION_ABBREV
UNION ALL
SELECT wheel.HOME_ORGANIZATION_ABBREV, wheel.HOME_COMPETITION_LEVEL_ABBREV, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.IS_STRIKE = TRUE THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS strike_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_RESULT = 'Swinging Strike' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS swing_k_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE = 'Fastball' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS fastball_rate,
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE <> 'Fastball' THEN 1 ELSE 0 END) / count(1)) DESC) AS breakball_rate
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel."YEAR" = 2022 
	AND wheel.IS_STRIKE IS NOT NULL AND wheel.PITCH_TYPE IS NOT NULL AND wheel.PITCH_RESULT IS NOT NULL
	AND wheel.HOME_COMPETITION_LEVEL_ABBREV = 'A+'
GROUP BY wheel.HOME_COMPETITION_LEVEL_ABBREV, wheel.HOME_ORGANIZATION_ABBREV
UNION ALL
SELECT wheel.HOME_ORGANIZATION_ABBREV, wheel.HOME_COMPETITION_LEVEL_ABBREV, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.IS_STRIKE = TRUE THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS strike_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_RESULT = 'Swinging Strike' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS swing_k_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE = 'Fastball' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS fastball_rate,
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE <> 'Fastball' THEN 1 ELSE 0 END) / count(1)) DESC) AS breakball_rate
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel."YEAR" = 2022 
	AND wheel.IS_STRIKE IS NOT NULL AND wheel.PITCH_TYPE IS NOT NULL AND wheel.PITCH_RESULT IS NOT NULL
	AND wheel.HOME_COMPETITION_LEVEL_ABBREV = 'AA'
GROUP BY wheel.HOME_COMPETITION_LEVEL_ABBREV, wheel.HOME_ORGANIZATION_ABBREV
UNION ALL
SELECT wheel.HOME_ORGANIZATION_ABBREV, wheel.HOME_COMPETITION_LEVEL_ABBREV, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.IS_STRIKE = TRUE THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS strike_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_RESULT = 'Swinging Strike' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS swing_k_rate, 
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE = 'Fastball' THEN 1 ELSE 0 END) / COUNT(1)) DESC) AS fastball_rate,
	RANK() OVER(ORDER BY (sum(CASE WHEN wheel.PITCH_TYPE <> 'Fastball' THEN 1 ELSE 0 END) / count(1)) DESC) AS breakball_rate
FROM rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel
WHERE wheel."YEAR" = 2022 
	AND wheel.IS_STRIKE IS NOT NULL AND wheel.PITCH_TYPE IS NOT NULL AND wheel.PITCH_RESULT IS NOT NULL
	AND wheel.HOME_COMPETITION_LEVEL_ABBREV = 'AAA'
GROUP BY wheel.HOME_COMPETITION_LEVEL_ABBREV, wheel.HOME_ORGANIZATION_ABBREV;