-- Query 1
SELECT hit.PLAYER_NAME_DISPLAY_LF, hit.WOBA FROM RPT.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.TEAM_NAME = 'Hickory Crawdads' AND hit."YEAR" = 2022 AND hit.PLATE_APPEARANCES > 155
GROUP BY hit.PLAYER_NAME_DISPLAY_LF, hit.WOBA 
ORDER BY hit.WOBA DESC;

-- Query 2
SELECT hit.PLAYER_NAME_DISPLAY_LF, hit.BALLS_IN_PLAY_TOTAL,
	100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / hit.BALLS_IN_PLAY_TOTAL AS quality_swing 
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.BALLS_IN_PLAY_TOTAL > 75 AND hit.TEAM_NAME = 'Frisco RoughRiders'
GROUP BY hit.PLAYER_NAME_DISPLAY_LF, hit.BALLS_IN_PLAY_TOTAL 
ORDER BY quality_swing DESC;

-- Query 3 (1)
SELECT hit.PLAYER_NAME_DISPLAY_LF AS lf, avg(hit.EXIT_SPEED_70) AS es70
FROM RPT.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.EXIT_SPEED_70  IS NOT NULL AND lf IS NOT NULL AND hit."YEAR" = 2022 
	AND hit.COMPETITION_LEVEL_SORT_ORDER > 10 AND hit.COMPETITION_LEVEL_SORT_ORDER < 300 AND hit.ORGANIZATION_ABBREV = 'TEX'
GROUP BY lf
ORDER BY es70 DESC
LIMIT 5;

SELECT hit.PLAYER_NAME_DISPLAY_LF AS lf, avg(hit.NITRO_PCT) AS nitro
FROM RPT.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.NITRO_PCT IS NOT NULL AND lf IS NOT NULL AND hit."YEAR" = 2022 
	AND hit.COMPETITION_LEVEL_SORT_ORDER > 10 AND hit.COMPETITION_LEVEL_SORT_ORDER < 300 AND hit.ORGANIZATION_ABBREV = 'TEX'
GROUP BY lf
ORDER BY nitro DESC
LIMIT 5;

SELECT hit.PLAYER_NAME_DISPLAY_LF AS lf, avg(hit.SWING_MISS_PCT) AS sm
FROM RPT.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.SWING_MISS_PCT IS NOT NULL AND lf IS NOT NULL AND hit."YEAR" = 2022 
	AND hit.COMPETITION_LEVEL_SORT_ORDER > 10 AND hit.COMPETITION_LEVEL_SORT_ORDER < 300 AND hit.ORGANIZATION_ABBREV = 'TEX'
GROUP BY lf HAVING sm > 0
ORDER BY sm
LIMIT 5;

SELECT hit.PLAYER_NAME_DISPLAY_LF AS lf, avg(hit.CHASE_PCT) AS ch
FROM RPT.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.CHASE_PCT IS NOT NULL AND lf IS NOT NULL AND hit."YEAR" = 2022 
	AND hit.COMPETITION_LEVEL_SORT_ORDER > 10 AND hit.COMPETITION_LEVEL_SORT_ORDER < 300 AND hit.ORGANIZATION_ABBREV = 'TEX'
GROUP BY lf HAVING ch > 0
ORDER BY ch
LIMIT 5;

SELECT hit.PLAYER_NAME_DISPLAY_LF AS lf, (100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL)) AS qual_swing
FROM RPT.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.BALLS_IN_PLAY_TOTAL > 0 AND lf IS NOT NULL AND hit."YEAR" = 2022 
	AND hit.COMPETITION_LEVEL_SORT_ORDER > 10 AND hit.COMPETITION_LEVEL_SORT_ORDER < 300 AND hit.ORGANIZATION_ABBREV = 'TEX'
GROUP BY lf 
ORDER BY qual_swing DESC
LIMIT 5;


-- Query 4
SELECT avg(hit.SWING_PCT) AS sw, avg(hit.SWING_MISS_PCT) AS sm, avg(hit.CHASE_PCT) AS ch,
	avg(hit.NITRO_PCT) AS nit, avg(hit.EXIT_SPEED) AS avg_ev, 
	(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL)) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
INNER JOIN rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel 
	ON wheel.BATTER_TXR_PLAYER_ID = hit.TXR_PLAYER_ID 
WHERE hit.PLAYER_NAME_DISPLAY_LF = 'Zavala, Aaron' AND wheel.RELEASE_SPEED > 93 AND wheel.PITCH_TYPE = 'Fastball';

-- Query 5 NOT DONE
SELECT gl.month(GAME_DATE) AS game_month, gl.NITRO AS nitro, 
FROM rpt.VIEW_GAME_LOG_BATTING AS gl
WHERE 



-- Query 6 UNABLE TO SPLIT PITCH TYPE AND RESULT BY LEVEL, ONLY METRICS
SELECT hit.COMPETITION_LEVEL_ABBREV AS minor_level, avg(hit.SWING_PCT) AS sw, avg(hit.SWING_MISS_PCT) AS sm, avg(hit.CHASE_PCT) AS ch,
	avg(hit.NITRO_PCT) AS nit, avg(hit.EXIT_SPEED) AS avg_ev, 
	(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL)) AS qual_swing,
	(sum(CASE WHEN wheel.PITCH_TYPE = 'Fastball' THEN 1 ELSE 0 END) / COUNT(1)) AS fastball_rate_a,
	(sum(CASE WHEN wheel.PITCH_TYPE <> 'Fastball' THEN 1 ELSE 0 END) / COUNT(1)) AS breakball_rate_a,
	(sum(CASE WHEN wheel.IS_HIGH = TRUE THEN 1 ELSE 0 END) / COUNT(1)) AS high_rate,
	(sum(CASE WHEN wheel.IS_LOW = TRUE THEN 1 ELSE 0 END) / COUNT(1)) AS low_rate,
	(sum(CASE WHEN wheel.IS_HIGH = FALSE AND wheel.IS_LOW = FALSE THEN 1 ELSE 0 END) / COUNT(1)) AS mid_rate
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
INNER JOIN rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel 
	ON wheel.BATTER_TXR_PLAYER_ID = hit.TXR_PLAYER_ID 
WHERE hit.PLAYER_NAME_DISPLAY_LF = 'Acuna, Luisangel' AND hit."YEAR" = 2022 AND hit.COMPETITION_LEVEL_ABBREV IN ('A+','AA') AND hit.COMPETITION_LEVEL_ABBREV IS NOT NULL
GROUP BY hit.COMPETITION_LEVEL_ABBREV;

-- Query 7 (General Performance)
SELECT hit.COMPETITION_LEVEL_ABBREV, avg(hit.SWING_PCT) AS sw, avg(hit.SWING_MISS_PCT) AS sm, avg(hit.CHASE_PCT) AS ch,
	avg(hit.NITRO_PCT) AS nit, avg(hit.EXIT_SPEED) AS avg_ev, 
	(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL)) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
INNER JOIN rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel 
	ON wheel.BATTER_TXR_PLAYER_ID = hit.TXR_PLAYER_ID 
WHERE hit.PLAYER_NAME_DISPLAY_LF = 'Duran, Ezequiel' AND wheel.SPIN_RATE > 2600 AND wheel.PITCH_TYPE <> 'Fastball' AND hit.COMPETITION_LEVEL_ABBREV IN ('AA','AAA')
	AND wheel.SPIN_RATE IS NOT NULL
GROUP BY hit.COMPETITION_LEVEL_ABBREV;

-- Query 7 (In and Out of Zone Split NOT WORKING)
SELECT hit.COMPETITION_LEVEL_ABBREV, wheel.IS_IN_STRIKE_ZONE, avg(hit.SWING_PCT) AS sw, avg(hit.SWING_MISS_PCT) AS sm, avg(hit.CHASE_PCT) AS ch,
	avg(hit.NITRO_PCT) AS nit, avg(hit.EXIT_SPEED) AS avg_ev, 
	(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL)) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
INNER JOIN rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel 
	ON wheel.BATTER_TXR_PLAYER_ID = hit.TXR_PLAYER_ID 
WHERE hit.PLAYER_NAME_DISPLAY_LF = 'Duran, Ezequiel' AND wheel.SPIN_RATE > 2600 AND wheel.PITCH_TYPE <> 'Fastball' AND hit.COMPETITION_LEVEL_ABBREV IN ('AA','AAA')
	AND wheel.SPIN_RATE IS NOT NULL AND wheel.IS_IN_STRIKE_ZONE = TRUE
GROUP BY hit.COMPETITION_LEVEL_ABBREV, wheel.IS_IN_STRIKE_ZONE
UNION ALL
SELECT hit.COMPETITION_LEVEL_ABBREV, wheel.IS_IN_STRIKE_ZONE, avg(hit.SWING_PCT) AS sw, avg(hit.SWING_MISS_PCT) AS sm, avg(hit.CHASE_PCT) AS ch,
	avg(hit.NITRO_PCT) AS nit, avg(hit.EXIT_SPEED) AS avg_ev, 
	(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL)) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
INNER JOIN rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel 
	ON wheel.BATTER_TXR_PLAYER_ID = hit.TXR_PLAYER_ID 
WHERE hit.PLAYER_NAME_DISPLAY_LF = 'Duran, Ezequiel' AND wheel.SPIN_RATE > 2600 AND wheel.PITCH_TYPE <> 'Fastball' AND hit.COMPETITION_LEVEL_ABBREV IN ('AA','AAA')
	AND wheel.SPIN_RATE IS NOT NULL AND wheel.IS_IN_STRIKE_ZONE = FALSE
GROUP BY hit.COMPETITION_LEVEL_ABBREV, wheel.IS_IN_STRIKE_ZONE;


-- Query 8 NOT SEPARATING BY HAND
SELECT avg(hit.SWING_PCT) AS sw, avg(hit.SWING_MISS_PCT) AS sm, avg(hit.CHASE_PCT) AS ch,
	avg(hit.NITRO_PCT) AS nit, avg(hit.EXIT_SPEED) AS avg_ev, 
	(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL)) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
INNER JOIN rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel 
	ON wheel.BATTER_TXR_PLAYER_ID = hit.TXR_PLAYER_ID 
WHERE hit.PLAYER_NAME_DISPLAY_LF = 'Crim, Blaine' AND wheel.pitcher_throws = 'R'
UNION ALL
SELECT avg(hit.SWING_PCT) AS sw, avg(hit.SWING_MISS_PCT) AS sm, avg(hit.CHASE_PCT) AS ch,
	avg(hit.NITRO_PCT) AS nit, avg(hit.EXIT_SPEED) AS avg_ev, 
	(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL)) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
INNER JOIN rpt.VIEW_WHEELHOUSE_PITCHES_MERGE AS wheel 
	ON wheel.BATTER_TXR_PLAYER_ID = hit.TXR_PLAYER_ID 
WHERE hit.PLAYER_NAME_DISPLAY_LF = 'Crim, Blaine' AND wheel.pitcher_throws = 'L';

-- Query 9 HOW TO FIND FIRST PITCH IN THE ZONE COLUMNS

-- Query 10 (All Levels Together)
SELECT hit.ORGANIZATION_ABBREV, RANK() OVER(ORDER BY avg(hit.SO_PCT)) AS k_rate, RANK() OVER(ORDER BY avg(hit.BB_PCT)) AS bb_rate,
	RANK() OVER(ORDER BY avg(hit.WOBA)) AS woba
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV IN ('A','A+','AA','AAA') AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.ORGANIZATION_ABBREV;

-- Query 10 (Separate Minor Levels)
SELECT hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(hit.SO_PCT)) AS k_rate, RANK() OVER(ORDER BY avg(hit.BB_PCT)) AS bb_rate,
	RANK() OVER(ORDER BY avg(hit.WOBA)) AS woba
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV = 'A' AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.COMPETITION_LEVEL_ABBREV, hit.ORGANIZATION_ABBREV
UNION ALL
SELECT hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(hit.SO_PCT)) AS k_rate, RANK() OVER(ORDER BY avg(hit.BB_PCT)) AS bb_rate,
	RANK() OVER(ORDER BY avg(hit.WOBA)) AS woba
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV = 'A+' AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.COMPETITION_LEVEL_ABBREV, hit.ORGANIZATION_ABBREV
UNION ALL
SELECT hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(hit.SO_PCT)) AS k_rate, RANK() OVER(ORDER BY avg(hit.BB_PCT)) AS bb_rate,
	RANK() OVER(ORDER BY avg(hit.WOBA)) AS woba
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV = 'AA' AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.COMPETITION_LEVEL_ABBREV, hit.ORGANIZATION_ABBREV
UNION ALL
SELECT hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(hit.SO_PCT)) AS k_rate, RANK() OVER(ORDER BY avg(hit.BB_PCT)) AS bb_rate,
	RANK() OVER(ORDER BY avg(hit.WOBA)) AS woba
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV = 'AAA' AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.COMPETITION_LEVEL_ABBREV, hit.ORGANIZATION_ABBREV;





-- Query 11 (All Levels Together)
SELECT hit.ORGANIZATION_ABBREV, RANK() OVER(ORDER BY avg(hit.SWING_MISS_PCT)) AS sm,
	RANK() OVER(ORDER BY avg(hit.CHASE_PCT)) AS ch, RANK() OVER(ORDER BY avg(hit.NITRO_PCT)) AS nit, 
	RANK() OVER(ORDER BY(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL))) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV IN ('A','A+','AA','AAA') AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.ORGANIZATION_ABBREV;


-- Query 11 (Separate Minor Levels)
SELECT hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(hit.SWING_MISS_PCT)) AS sm,
	RANK() OVER(ORDER BY avg(hit.CHASE_PCT)) AS ch, RANK() OVER(ORDER BY avg(hit.NITRO_PCT)) AS nit, 
	RANK() OVER(ORDER BY(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL))) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV = 'A' AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV 
UNION ALL
SELECT hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(hit.SWING_MISS_PCT)) AS sm,
	RANK() OVER(ORDER BY avg(hit.CHASE_PCT)) AS ch, RANK() OVER(ORDER BY avg(hit.NITRO_PCT)) AS nit, 
	RANK() OVER(ORDER BY(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL))) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV = 'A+' AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV 
UNION ALL
SELECT hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(hit.SWING_MISS_PCT)) AS sm,
	RANK() OVER(ORDER BY avg(hit.CHASE_PCT)) AS ch, RANK() OVER(ORDER BY avg(hit.NITRO_PCT)) AS nit, 
	RANK() OVER(ORDER BY(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL))) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV = 'AA' AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV 
UNION ALL
SELECT hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV, RANK() OVER(ORDER BY avg(hit.SWING_MISS_PCT)) AS sm,
	RANK() OVER(ORDER BY avg(hit.CHASE_PCT)) AS ch, RANK() OVER(ORDER BY avg(hit.NITRO_PCT)) AS nit, 
	RANK() OVER(ORDER BY(100.0 * SUM(CASE WHEN hit.LAUNCH_ANGLE > 10 AND hit.LAUNCH_ANGLE < 30 THEN 1 ELSE 0 END) / sum(hit.BALLS_IN_PLAY_TOTAL))) AS qual_swing
FROM rpt.VIEW_AGG_HIT_PLAYER AS hit
WHERE hit.COMPETITION_LEVEL_ABBREV = 'AAA' AND hit.ORGANIZATION_ABBREV <> 'XX'
GROUP BY hit.ORGANIZATION_ABBREV, hit.COMPETITION_LEVEL_ABBREV;
