---
title: "Individual Pitcher Arsenal Variation by Runner State and Outs"
author: "Alexander Harriman"
date: "2024-03-12"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, warning = FALSE, include = FALSE}
library(baseballr)
library(tidyverse)
library(gt)
library(flexdashboard)
library(weights)
```


```{r, include = FALSE}
ids <- read.csv('MLBPlayerIDs.csv')

ids
```


```{r, include = FALSE}
playerInput <- 'Blake Snell'

playerID <- ids |>
  filter(Name == playerInput) |>
  select(MLBAMID)

inputID <- playerID$MLBAMID[1]
```



```{r, include = FALSE}
# Get the PBP Data
pitcherData <- statcast_search_pitchers(start_date = '2023-03-30', end_date = '2023-11-01', pitcherid = inputID)

head(pitcherData)
```

```{r, include = FALSE}
runnersData <- pitcherData |>
  mutate(base_state = case_when(
    is.na(on_3b) == TRUE & is.na(on_2b) == TRUE & is.na(on_1b) == TRUE ~ 'Bases Empty',
    is.na(on_3b) == TRUE & is.na(on_2b) == TRUE & is.na(on_1b) == FALSE ~ 'Runner on 1st Only',
    is.na(on_3b) == FALSE | is.na(on_2b) == FALSE ~ 'Runner(s) in Scoring Position'
  ))
```




Full-Season Summary
======================================

**Pitcher: `r playerInput`**

Usage {data-height=500}
-------------------------------------

```{r, echo = FALSE}
arsenal <- runnersData |>
  group_by(base_state) |>
  summarise(n = length(base_state),
            FBs = round(100.0*sum(ifelse(pitch_name %in% c('Split-Finger', '4-Seam Fastball'), 1, 0)) / n, 1),
            SIs = round(100.0*sum(ifelse(pitch_name == 'Sinker', 1, 0)) / n, 1),
            CUs = round(100.0*sum(ifelse(pitch_name == 'Cutter', 1, 0)) / n, 1),
            SLs = round(100.0*sum(ifelse(pitch_name == 'Slider', 1, 0)) / n, 1),
            CBs = round(100.0*sum(ifelse(pitch_name == 'Curveball', 1, 0)) / n, 1),
            CHs = round(100.0*sum(ifelse(pitch_name == 'Changeup', 1, 0)) / n, 1))


finalArsenal <- arsenal |>
  gt() |>
  tab_header(title = md('**2023 Arsenal by Base State**')) |>
  cols_align(align = 'center', columns = c('n', 'FBs', 'SIs', 'SLs', 'CUs', 'CBs', 'CHs')) |>
  cols_label(base_state = 'Base State', 
             n = '# Pitches', 
             FBs = 'FB%', 
             SIs = 'SI%', 
             SLs = 'SL%',
             CUs = 'CU%',
             CBs = 'CB%',
             CHs = 'CH%') |>
  opt_stylize(style = 5, color = 'blue') |>
  cols_width(base_state ~ px(250), n ~ px(75), everything() ~ px(60)) |>
  tab_footnote('Includes Postseason')

finalArsenal
```



Results {data-height=500}
--------------------------------

```{r, echo = FALSE}
results <- runnersData |>
  group_by(base_state) |>
  summarise(PA = n_distinct(paste(game_pk,at_bat_number)),
            BA = rd(sum(ifelse(events %in% c('single', 'double', 'triple', 'home_run'), 1, 0)) / 
            sum(ifelse(events %in% c('strikeout', 'single', 'field_out', 'force_out', 'double', 'grounded_into_double_play', 'home_run', 'other_out', 'double_play'), 1, 0)),3),
            OBP = rd(sum(ifelse(events %in% c('single', 'double', 'triple', 'home_run', 'walk', 'hit_by_pitch'), 1, 0)) /
            sum(ifelse(events %in% c('strikeout', 'single', 'field_out', 'force_out', 'double', 'grounded_into_double_play', 'home_run', 'other_out', 'double_play', 'walk', 'hit_by_pitch', 'sac_fly', 'fielders_choice_out'), 1, 0)),3),
            SLG = rd(sum(case_when(
              events == 'single' ~ 1,
              events == 'double' ~ 2, 
              events == 'triple' ~ 3,
              events == 'home_run' ~ 4,
              .default = 0
            )) / 
            sum(ifelse(events %in% c('strikeout', 'single', 'field_out', 'force_out', 'double', 'grounded_into_double_play', 'home_run', 'other_out', 'double_play'), 1, 0)),3),
            wOBA = rd(sum(case_when(
              events == 'walk' ~ 0.696,
              events == 'hit_by_pitch' ~ 0.726,
              events == 'single' ~ 0.883,
              events == 'double' ~ 1.244,
              events == 'triple' ~ 1.569,
              events == 'home_run' ~ 2.004,
              .default = 0
            )) / sum(woba_denom, na.rm = TRUE),3),
            GBs = round(100.0*sum(ifelse(bb_type == 'ground_ball', 1, 0)) /
                  sum(ifelse(description == 'hit_into_play', 1, 0)),1))
          


finalResults <- results |>
  gt() |>
  tab_header(title = md('**2023 Results by Base State**')) |>
  cols_align(align = 'center', columns = c('PA', 'BA', 'OBP', 'SLG', 'wOBA', 'GBs')) |>
  cols_label(base_state = 'Base State', 
             GBs = 'GB%') |>
  opt_stylize(style = 5, color = 'gray') |>
  cols_width(base_state ~ px(250), everything() ~ px(72.5)) |>
  tab_footnote('Includes Postseason')

finalResults
```


2 Outs
======================================

**Pitcher: `r playerInput`**

```{r, include = FALSE}
runnersOutsData <- runnersData |>
  filter(outs_when_up == 2)
```


Usage {data-height=500}
-------------------------------------

```{r, echo = FALSE}
arsenal2 <- runnersOutsData |>
  group_by(base_state) |>
  summarise(n = length(base_state),
            FBs = round(100.0*sum(ifelse(pitch_name %in% c('Split-Finger', '4-Seam Fastball'), 1, 0)) / n, 1),
            SIs = round(100.0*sum(ifelse(pitch_name == 'Sinker', 1, 0)) / n, 1),
            CUs = round(100.0*sum(ifelse(pitch_name == 'Cutter', 1, 0)) / n, 1),
            SLs = round(100.0*sum(ifelse(pitch_name == 'Slider', 1, 0)) / n, 1),
            CBs = round(100.0*sum(ifelse(pitch_name == 'Curveball', 1, 0)) / n, 1),
            CHs = round(100.0*sum(ifelse(pitch_name == 'Changeup', 1, 0)) / n, 1))


finalArsenal2 <- arsenal2 |>
  gt() |>
  tab_header(title = md('**2023 Arsenal By Base State, 2 Outs**')) |>
  cols_align(align = 'center', columns = c('n', 'FBs', 'SIs', 'SLs', 'CUs', 'CBs', 'CHs')) |>
  cols_label(base_state = 'Base State', 
             n = '# Pitches', 
             FBs = 'FB%', 
             SIs = 'SI%', 
             SLs = 'SL%',
             CUs = 'CU%',
             CBs = 'CB%',
             CHs = 'CH%') |>
  opt_stylize(style = 5, color = 'blue') |>
  cols_width(base_state ~ px(250), n ~ px(75), everything() ~ px(60)) |>
  tab_footnote('Includes Postseason')

finalArsenal2
```



Results {data-height=500}
--------------------------------

```{r, echo = FALSE}
results2 <- runnersOutsData |>
  group_by(base_state) |>
  summarise(PA = n_distinct(paste(game_pk,at_bat_number)),
            BA = rd(sum(ifelse(events %in% c('single', 'double', 'triple', 'home_run'), 1, 0)) / 
            sum(ifelse(events %in% c('strikeout', 'single', 'field_out', 'force_out', 'double', 'grounded_into_double_play', 'home_run', 'other_out', 'double_play'), 1, 0)),3),
            OBP = rd(sum(ifelse(events %in% c('single', 'double', 'triple', 'home_run', 'walk', 'hit_by_pitch'), 1, 0)) /
            sum(ifelse(events %in% c('strikeout', 'single', 'field_out', 'force_out', 'double', 'grounded_into_double_play', 'home_run', 'other_out', 'double_play', 'walk', 'hit_by_pitch', 'sac_fly', 'fielders_choice_out'), 1, 0)),3),
            SLG = rd(sum(case_when(
              events == 'single' ~ 1,
              events == 'double' ~ 2, 
              events == 'triple' ~ 3,
              events == 'home_run' ~ 4,
              .default = 0
            )) / 
            sum(ifelse(events %in% c('strikeout', 'single', 'field_out', 'force_out', 'double', 'grounded_into_double_play', 'home_run', 'other_out', 'double_play'), 1, 0)),3),
            wOBA = rd(sum(case_when(
              events == 'walk' ~ 0.696,
              events == 'hit_by_pitch' ~ 0.726,
              events == 'single' ~ 0.883,
              events == 'double' ~ 1.244,
              events == 'triple' ~ 1.569,
              events == 'home_run' ~ 2.004,
              .default = 0
            )) / sum(woba_denom, na.rm = TRUE),3),
            GBs = round(100.0*sum(ifelse(bb_type == 'ground_ball', 1, 0)) /
                  sum(ifelse(description == 'hit_into_play', 1, 0)),1))
          


finalResults2 <- results2 |>
  gt() |>
  tab_header(title = md('**2023 Results by Base State, 2 Outs**')) |>
  cols_align(align = 'center', columns = c('PA', 'BA', 'OBP', 'SLG', 'wOBA', 'GBs')) |>
  cols_label(base_state = 'Base State', 
             GBs = 'GB%') |>
  opt_stylize(style = 5, color = 'gray') |>
  cols_width(base_state ~ px(250), everything() ~ px(72.5)) |>
  tab_footnote('Includes Postseason')

finalResults2
```


0-1 Outs
=======================================

**Pitcher: `r playerInput`**


```{r, include = FALSE}
runnersOutData <- runnersData |>
  filter(outs_when_up < 2)
```


Usage {data-height=500}
-------------------------------------

```{r, echo = FALSE}
arsenal3 <- runnersOutData |>
  group_by(base_state) |>
  summarise(n = length(base_state),
            FBs = round(100.0*sum(ifelse(pitch_name %in% c('Split-Finger', '4-Seam Fastball'), 1, 0)) / n, 1),
            SIs = round(100.0*sum(ifelse(pitch_name == 'Sinker', 1, 0)) / n, 1),
            CUs = round(100.0*sum(ifelse(pitch_name == 'Cutter', 1, 0)) / n, 1),
            SLs = round(100.0*sum(ifelse(pitch_name == 'Slider', 1, 0)) / n, 1),
            CBs = round(100.0*sum(ifelse(pitch_name == 'Curveball', 1, 0)) / n, 1),
            CHs = round(100.0*sum(ifelse(pitch_name == 'Changeup', 1, 0)) / n, 1))


finalArsenal3 <- arsenal3 |>
  gt() |>
  tab_header(title = md('**2023 Arsenal by Base State, 0-1 Outs**')) |>
  cols_align(align = 'center', columns = c('n', 'FBs', 'SIs', 'SLs', 'CUs', 'CBs', 'CHs')) |>
  cols_label(base_state = 'Base State', 
             n = '# Pitches', 
             FBs = 'FB%', 
             SIs = 'SI%', 
             SLs = 'SL%',
             CUs = 'CU%',
             CBs = 'CB%',
             CHs = 'CH%') |>
  opt_stylize(style = 5, color = 'blue') |>
  cols_width(base_state ~ px(250), n ~ px(75), everything() ~ px(60)) |>
  tab_footnote('Includes Postseason')

finalArsenal3
```



Results {data-height=500}
--------------------------------

```{r, echo = FALSE}
results3 <- runnersOutData |>
  group_by(base_state) |>
  summarise(PA = n_distinct(paste(game_pk,at_bat_number)),
            BA = rd(sum(ifelse(events %in% c('single', 'double', 'triple', 'home_run'), 1, 0)) / 
            sum(ifelse(events %in% c('strikeout', 'single', 'field_out', 'force_out', 'double', 'grounded_into_double_play', 'home_run', 'other_out', 'double_play'), 1, 0)),3),
            OBP = rd(sum(ifelse(events %in% c('single', 'double', 'triple', 'home_run', 'walk', 'hit_by_pitch'), 1, 0)) /
            sum(ifelse(events %in% c('strikeout', 'single', 'field_out', 'force_out', 'double', 'grounded_into_double_play', 'home_run', 'other_out', 'double_play', 'walk', 'hit_by_pitch', 'sac_fly', 'fielders_choice_out'), 1, 0)),3),
            SLG = rd(sum(case_when(
              events == 'single' ~ 1,
              events == 'double' ~ 2, 
              events == 'triple' ~ 3,
              events == 'home_run' ~ 4,
              .default = 0
            )) / 
            sum(ifelse(events %in% c('strikeout', 'single', 'field_out', 'force_out', 'double', 'grounded_into_double_play', 'home_run', 'other_out', 'double_play'), 1, 0)),3),
            wOBA = rd(sum(case_when(
              events == 'walk' ~ 0.696,
              events == 'hit_by_pitch' ~ 0.726,
              events == 'single' ~ 0.883,
              events == 'double' ~ 1.244,
              events == 'triple' ~ 1.569,
              events == 'home_run' ~ 2.004,
              .default = 0
            )) / sum(woba_denom, na.rm = TRUE),3),
            GBs = round(100.0*sum(ifelse(bb_type == 'ground_ball', 1, 0)) /
                  sum(ifelse(description == 'hit_into_play', 1, 0)),1))
          


finalResults3 <- results3 |>
  gt() |>
  tab_header(title = md('**2023 Results by Base State, 0-1 Outs**')) |>
  cols_align(align = 'center', columns = c('PA', 'BA', 'OBP', 'SLG', 'wOBA', 'GBs')) |>
  cols_label(base_state = 'Base State', 
             GBs = 'GB%') |>
  opt_stylize(style = 5, color = 'gray') |>
  cols_width(base_state ~ px(250), everything() ~ px(72.5)) |>
  tab_footnote('Includes Postseason')

finalResults3
```

