---
title: "Individual Pitcher Arsenal Variation by Runner State"
author: "Alexander Harriman"
date: "2024-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, warning = FALSE}
library(baseballr)
library(tidyverse)
library(gt)
```



```{r}
# Get the PBP Data
monty <- statcast_search_pitchers(start_date = '2023-03-30', end_date = '2023-11-01', pitcherid = 656756)

head(monty)
```

# Separate Data by Runner State

```{r}
cleanMonty <- monty |>
  mutate(base_state = case_when(
    is.na(on_3b) == TRUE & is.na(on_2b) == TRUE & is.na(on_1b) == TRUE ~ 'Bases Empty',
    is.na(on_3b) == TRUE & is.na(on_2b) == TRUE & is.na(on_1b) == FALSE ~ 'Runner on 1st Only',
    is.na(on_3b) == FALSE | is.na(on_2b) == FALSE ~ 'Runner(s) in Scoring Position'
  ))

summary <- cleanMonty |>
  group_by(base_state) |>
  summarise(n = length(base_state),
            FBs = round(100.0*sum(ifelse(pitch_name %in% c('Split-Finger', '4-Seam Fastball'), 1, 0)) / n, 1),
            SIs = round(100.0*sum(ifelse(pitch_name == 'Sinker', 1, 0)) / n, 1),
            CUs = round(100.0*sum(ifelse(pitch_name == 'Cutter', 1, 0)) / n, 1),
            CBs = round(100.0*sum(ifelse(pitch_name == 'Curveball', 1, 0)) / n, 1),
            CHs = round(100.0*sum(ifelse(pitch_name == 'Changeup', 1, 0)) / n, 1))

summary

```




```{r}
finalTable <- summary |>
  gt() |>
  tab_header(title = md('**Jordan Montgomery Arsenal by Base State, 2023**')) |>
  cols_align(align = 'center', columns = c('n', 'FBs', 'SIs', 'CUs', 'CBs', 'CHs')) |>
  cols_label(base_state = 'Base State', 
             n = '# Pitches', 
             FBs = 'FB%', 
             SIs = 'SI%', 
             CUs = 'CU%',
             CBs = 'CB%',
             CHs = 'CH%') |>
  opt_stylize(style = 5, color = 'blue') |>
  cols_width(base_state ~ px(250), n ~ px(75), everything() ~ px(60)) |>
  tab_footnote('Includes Postseason')

finalTable
```